{% set name = "brainglobe-napari-io" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/brainglobe-napari-io-{{ version }}.tar.gz
  sha256: bb0822460d9063d6c48dbd43618284d0eb65d1f539bbb02ee90addf67e4d5de5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - brainglobe-atlasapi
    - brainglobe-space
    - brainglobe-utils
    - napari
    - numpy
    - pandas
    - python >={{ python_min }}
    - tifffile >=2020.8.13

test:
  imports:
    - brainglobe_napari_io
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://brainglobe.info
  summary: Read and write files from the BrainGlobe neuroanatomy suite
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/brainglobe/brainglobe-napari-io

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
    - jaimergp
