{% set name = "brainglobe-napari-io" %}
{% set version = "0.3.5" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b8ad0e307406f1019acbbf5d5761bda5e207bcaaf217a74756365dd55bf63566

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - brainglobe-atlasapi
    - brainglobe-space
    - brainglobe-utils
    - napari <0.6.0
    - numpy
    - pandas
    - python >={{ python_min }}
    - qt-niu
    - tifffile >=2020.8.13

test:
  imports:
    - brainglobe_napari_io
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://brainglobe.info
  summary: Read and write files from the BrainGlobe neuroanatomy suite
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/brainglobe/brainglobe-napari-io

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
    - jaimergp
